import { Module } from "@nestjs/common";
import { TypeOrmModule } from "@nestjs/typeorm";

import {
  BaseAppUpdateEntity,
  BaseBodyParamEntity,
  BaseFoodGroupEntity,
  BaseFoodNutrientEntity,
  BaseFoodEntity,
  BaseMealFoodEntity,
  BaseMealEntity,
  BaseMuscleEntity,
  BaseNutrientEntity,
  BaseUnitEntity,
  BaseWorkoutHowtoPerformStepEntity,
  BaseWorkoutNutrientBurnEntity,
  BaseWorkoutRecommendedRepetitionEntity,
  BaseWorkoutEntity,
  BaseNutritionTypeEntity,
  BaseSociologyEntity,
  BaseSociologyGroupEntity,
  BaseNutritionEntity
} from "./entity";


import {
  BaseAppUpdateService,
  BaseBodyParamService,
  BaseFoodGroupService,
  BaseFoodNutrientService,
  BaseFoodService,
  BaseMealFoodService,
  BaseMealService,
  BaseMuscleService,
  BaseNutrientService,
  BaseNutritionTypeService,
  BaseUnitService,
  BaseWorkoutHowtoPerformStepService,
  BaseWorkoutNutrientBurnService,
  BaseWorkoutRecommendedRepetitionService,
  BaseWorkoutService,
  BaseSociologyService,
  BaseSociologyGroupService,
  BaseNutritionService
} from "./service";

import {
  BaseAppUpdateController,
  BaseBodyParamController,
  BaseFoodGroupController,
  BaseFoodNutrientController,
  BaseFoodController,
  BaseMealFoodController,
  BaseMealController,
  BaseMuscleController,
  BaseNutrientController,
  BaseUnitController,
  BaseWorkoutHowtoPerformStepController,
  BaseWorkoutNutrientBurnController,
  BaseWorkoutRecommendedRepetitionController,
  BaseWorkoutController,
  BaseSociologyController,
  BaseSociologyGroupController,
  BaseNutritionController,
  BaseNutritionTypeController

} from "./controller";


@Module({
  imports: [
    TypeOrmModule.forFeature([
      BaseAppUpdateEntity,
      BaseBodyParamEntity,
      BaseFoodGroupEntity,
      BaseFoodNutrientEntity,
      BaseFoodEntity,
      BaseMealFoodEntity,
      BaseMealEntity,
      BaseMuscleEntity,
      BaseNutrientEntity,
      BaseNutritionEntity,
      BaseNutritionTypeEntity,
      BaseUnitEntity,
      BaseWorkoutHowtoPerformStepEntity,
      BaseWorkoutNutrientBurnEntity,
      BaseWorkoutRecommendedRepetitionEntity,
      BaseWorkoutEntity,
      BaseSociologyEntity,
      BaseSociologyGroupEntity,
    ])],
  controllers: [
    BaseAppUpdateController,
    BaseBodyParamController,
    BaseFoodGroupController,
    BaseFoodNutrientController,
    BaseFoodController,
    BaseMealFoodController,
    BaseMealController,
    BaseMuscleController,
    BaseNutrientController,
    BaseNutritionTypeController,
    BaseNutritionController,
    BaseUnitController,
    BaseWorkoutHowtoPerformStepController,
    BaseWorkoutNutrientBurnController,
    BaseWorkoutRecommendedRepetitionController,
    BaseWorkoutController,
    BaseSociologyController,
    BaseSociologyGroupController
  ],
  providers: [
    BaseAppUpdateService,
    BaseBodyParamService,
    BaseFoodGroupService,
    BaseFoodNutrientService,
    BaseFoodService,
    BaseMealFoodService,
    BaseMealService,
    BaseMuscleService,
    BaseNutrientService,
    BaseNutritionTypeService,
    BaseNutritionService,
    BaseUnitService,
    BaseWorkoutHowtoPerformStepService,
    BaseWorkoutNutrientBurnService,
    BaseWorkoutRecommendedRepetitionService,
    BaseWorkoutService,
    BaseSociologyService,
    BaseSociologyGroupService
  ],
  exports: [
    BaseAppUpdateService,
    BaseBodyParamService,
    BaseFoodGroupService,
    BaseFoodNutrientService,
    BaseFoodService,
    BaseMealFoodService,
    BaseMealService,
    BaseMuscleService,
    BaseNutrientService,
    BaseNutritionTypeService,
    BaseNutritionService,
    BaseUnitService,
    BaseWorkoutHowtoPerformStepService,
    BaseWorkoutNutrientBurnService,
    BaseWorkoutRecommendedRepetitionService,
    BaseWorkoutService,
    BaseSociologyService,
    BaseSociologyGroupService
  ],
})
export class BaseModule {}
