import { Module } from "@nestjs/common";



import { TypeOrmModule } from "@nestjs/typeorm";

import {
  BaseAppUpdateEntity,
  BaseBodyParamEntity,
  BaseFoodGroupEntity,
  BaseFoodNutrientEntity,
  BaseFoodEntity,
  BaseMealFoodEntity,
  BaseMealEntity,
  BaseMuscleEntity,
  BaseNutrientEntity,
  BaseUnitEntity,
  BaseWorkoutHowtoPerformStepEntity,
  BaseWorkoutNutrientBurnEntity,
  BaseWorkoutRecommendedRepetitionEntity,
  BaseWorkoutEntity,
  BaseNutritionTypeEntity,
  BaseSociologyEntity,
  BaseSociologyGroupEntity,
  BaseNutritionEntity,
  BaseNutritionToolEntity,
  BaseRecipeItemEntity,
  BaseRecipeInstructionTagEntity,
  BaseRecipeInstructionEntity,
  BaseRecipeEntity,
  BaseCurrencyEntity,
  BaseProgramGoalEntity
} from "./entity";


import {
  BaseAppUpdateService,
  BaseBodyParamService,
  BaseFoodGroupService,
  BaseFoodNutrientService,
  BaseFoodService,
  BaseMealFoodService,
  BaseMealService,
  BaseMuscleService,
  BaseNutrientService,
  BaseNutritionTypeService,
  BaseUnitService,
  BaseWorkoutHowtoPerformStepService,
  BaseWorkoutNutrientBurnService,
  BaseWorkoutRecommendedRepetitionService,
  BaseWorkoutService,
  BaseSociologyService,
  BaseSociologyGroupService,
  BaseNutritionService,
  BaseNutritionToolService,
  BaseRecipeItemService,
  BaseRecipeInstructionTagService,
  BaseRecipeInstructionService,
  BaseRecipeService,
  BaseCurrencyService,
  BaseProgramGoalService
} from "./service"; // Added BaseProgramGoalService

import {
  BaseAppUpdateController,
  BaseBodyParamController,
  BaseFoodGroupController,
  BaseFoodNutrientController,
  BaseFoodController,
  BaseMealFoodController,
  BaseMealController,
  BaseMuscleController,
  BaseNutrientController,
  BaseUnitController,
  BaseWorkoutHowtoPerformStepController,
  BaseWorkoutNutrientBurnController,
  BaseWorkoutRecommendedRepetitionController,
  BaseWorkoutController,
  BaseSociologyController,
  BaseSociologyGroupController,
  BaseNutritionController,
  BaseNutritionTypeController,
  BaseNutritionToolController,
  BaseRecipeItemController,
  BaseRecipeInstructionTagController,
  BaseRecipeInstructionController,
  BaseRecipeController,
  BaseCurrencyController,
  BaseProgramGoalController
} from "./controller"; // Added BaseProgramGoalController


@Module({
  imports: [
    TypeOrmModule.forFeature([
      BaseAppUpdateEntity,
      BaseBodyParamEntity,
      BaseFoodGroupEntity,
      BaseFoodNutrientEntity,
      BaseFoodEntity,
      BaseMealFoodEntity,
      BaseMealEntity,
      BaseMuscleEntity,
      BaseNutrientEntity,
      BaseNutritionEntity,
      BaseNutritionToolEntity,
      BaseRecipeItemEntity,
      BaseRecipeInstructionTagEntity,
      BaseRecipeInstructionEntity,
      BaseNutritionTypeEntity,
      BaseUnitEntity,
      BaseWorkoutHowtoPerformStepEntity,
      BaseWorkoutNutrientBurnEntity,
      BaseWorkoutRecommendedRepetitionEntity,
      BaseWorkoutEntity,
      BaseSociologyEntity,
      BaseSociologyGroupEntity,
      BaseRecipeEntity,
      BaseCurrencyEntity,
      BaseProgramGoalEntity
    ])],
  controllers: [
    BaseAppUpdateController,
    BaseBodyParamController,
    BaseFoodGroupController,
    BaseFoodNutrientController,
    BaseFoodController,
    BaseMealFoodController,
    BaseMealController,
    BaseMuscleController,
    BaseNutrientController,
    BaseNutritionTypeController,
    BaseNutritionToolController,
    BaseRecipeItemController,
    BaseRecipeInstructionTagController,
    BaseRecipeInstructionController,
    BaseNutritionController,
    BaseUnitController,
    BaseWorkoutHowtoPerformStepController,
    BaseWorkoutNutrientBurnController,
    BaseWorkoutRecommendedRepetitionController,
    BaseWorkoutController,
    BaseSociologyController,
    BaseSociologyGroupController,
    BaseRecipeController,
    BaseCurrencyController,
    BaseProgramGoalController
  ],
  providers: [
    BaseAppUpdateService,
    BaseBodyParamService,
    BaseFoodGroupService,
    BaseFoodNutrientService,
    BaseFoodService,
    BaseMealFoodService,
    BaseMealService,
    BaseMuscleService,
    BaseNutrientService,
    BaseNutritionTypeService,
    BaseNutritionService,
    BaseRecipeService,
    BaseUnitService,
    BaseWorkoutHowtoPerformStepService,
    BaseWorkoutNutrientBurnService,
    BaseWorkoutRecommendedRepetitionService,
    BaseWorkoutService,
    BaseSociologyService,
    BaseSociologyGroupService,
    BaseNutritionToolService,
    BaseRecipeItemService,
    BaseRecipeInstructionTagService,
    BaseRecipeInstructionService,
    BaseCurrencyService,
    BaseProgramGoalService
  ],
  exports: [
    BaseAppUpdateService,
    BaseBodyParamService,
    BaseFoodGroupService,
    BaseFoodNutrientService,
    BaseFoodService,
    BaseMealFoodService,
    BaseMealService,
    BaseMuscleService,
    BaseNutrientService,
    BaseNutritionTypeService,
    BaseNutritionService,
    BaseRecipeService,
    BaseUnitService,
    BaseWorkoutHowtoPerformStepService,
    BaseWorkoutNutrientBurnService,
    BaseWorkoutRecommendedRepetitionService,
    BaseWorkoutService,
    BaseSociologyService,
    BaseSociologyGroupService,
    BaseNutritionToolService,
    BaseRecipeItemService,
    BaseRecipeInstructionTagService,
    BaseRecipeInstructionService,
    BaseCurrencyService,
    BaseProgramGoalService
  ],
})
export class BaseModule {}
