services:
  moneydey-npf-api-postgre-db:
    image: postgis/postgis:17-3.5
    restart: always
    container_name: moneydey-npf-api-postgre-db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - moneydey-npf-api-postgre-volume:${PGDATA}/:rw
      - ./docker/postgres/db-exists.sh:/usr/bin/db-exists.sh
      - ./docker/postgres/create-database.sh:/usr/bin/create-database.sh
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - moneydey-infra-network

  moneydey-npf-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneydey-npf-api
    env_file:
      - .env
    depends_on:
      moneydey-npf-api-postgre-db:
        condition: service_healthy
      flyway:
        condition: service_started
    volumes:
      - .:/usr/app
    networks:
      - moneydey-infra-network

  flyway:
    build:
      context: .
      dockerfile: docker/flyway/Dockerfile
    container_name: nextupfit-flyway
    env_file:
      - .env
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      moneydey-npf-api-postgre-db:
        condition: service_healthy
    networks:
      - moneydey-infra-network

networks:
  moneydey-infra-network:
    external: true

volumes:
  moneydey-npf-api-postgre-volume:
    external: true

