services:
  db:
    image: postgres:16
    restart: always
    container_name: nextupfit-postgres
    hostname: nextupfitdb
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextupfit_db
      - POSTGRES_SHARED_BUFFERS=1GB  # Increase shared buffers to 1GB
      - POSTGRES_WORK_MEM=128MB      # Allocate 128MB for work_mem
      - POSTGRES_MAX_CONNECTIONS=200 # Increase max connections to 200
      - POSTGRES_CHECKPOINT_TIMEOUT=10min  # Adjust checkpoint frequency
      - POSTGRES_CHECKPOINT_COMPLETION_TARGET=0.7  # Allow 70% time for checkpoint completion
      - POSTGRES_WAL_BUFFERS=16MB    # Set WAL buffers to 16MB
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - nextupfit-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextupfit-api
    environment:
      - PORT=3000
      - DATABASE_NAME=nextupfit_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=nextupfitdb
      - DATABASE_DIALECT=postgres
      - DATABASE_PORT=5432
      - JWT_SECRET=fitness_coach_platform_jwt_secret
      - JWT_REFRESH_SECRET=fitness_coach_platform_jwt_refresh_secret
      - STRIPE_SECRET_KEY=sk_test_51PlrNnAyVkDWU93S1gjnZZkhjHqKPvI3Iq8IZAHsC4T8UZsAB3w58dMTNNFaipfbS7fRsuq7UsPyWxIwzNBLKh4N00BWY54Dzp
      - MAIL_HOST=live.smtp.mailtrap.io
      - MAIL_PORT=587
      - MAIL_USER=api
      - MAIL_PASS=c03c90bedb457d8a4578b30200743192
      - MAIL_FROM=mailtrap@demomailtrap.com
      - MAIL_SECURE=false
      - APP_URL=http://localhost:3000
      - APP_NAME=NextUpFit
      - FB_TYPE=service_account
      - FB_PROJECT_ID=nextupfit-8f1e6
      - FB_PRIVATE_KEY_ID=c9a36a20706d3b30c80b1f8f9f9f468cd8c94fba
      - FB_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvg11YmWEDlgLv\nOYWaT/6VLBLErGfsioM6D+3LLZG7mVK6NAs80/tob5rtlge0bU8zOl...
      - FB_CLIENT_EMAIL=firebase-adminsdk-fwdqs@nextupfit-8f1e6.iam.gserviceaccount.com
      - FB_CLIENT_ID=104096796052252345936
      - FB_AUTH_URI=https://accounts.google.com/o/oauth2/auth
      - FB_TOKEN_URI=https://oauth2.googleapis.com/token
      - AUTH_PROVIDE_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
      - FB_CLIENT_X509_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fwdqs%40nextupfit-8f1e6.iam.gserviceaccount.com
      - FB_UNIVERSE_DOMAIN=googleapis.com
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/app
    networks:
      - nextupfit-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nextupfit-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nextupfit-network

  nginx:
    image: nginx:alpine
    container_name: nextupfit-nginx
    volumes:
      - postgres-data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - nextupfit-network

networks:
  nextupfit-network:
    driver: bridge

volumes:
  postgres-data:
  nginx-data:

