export enum BaseBodyPartEnum {
  head = "head",
  shoulder = "shoulder",
  neck = "neck",
  arms = "arms",
  hands = "hands",
  chest = "chest",
  stomac = "stomac",
  back = "back",
  ribs = "ribs",
  hips = "hips",
  kidneybelt = "kidneybelt",
  buttocks = "buttocks",
  thighs = "thighs",
  hamstrings = "hamstrings",
  knees = "knees",
  wrists = "wrists",
  elbows = "elbows",
  ankles = "ankles",
  calves = "calves",
  shins = "shins",
  feets = "feets",
  phalanges = "phalanges",
  toes = "toes",
  sinus = "sinus",
  forearm = "forearm",
  uppertrapezius = "uppertrapezius",
}
