import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  GymController,
  GymFollowerController,
  GymManagerController,
  GymManagerOverviewController,
  GymManagerQualificationController,
  GymManagerSpecializedInWorkoutController,
  GymMembershipPlanController,
  GymManagerFollowerController,
  GymManagerRequestController,
  GymMembershipController,
  GymSpecializedInWorkoutController,
  GymSpecializedInNutritionController,
  GymManagerSpecializedInNutritionController,
  GymOpenDayController,
} from './controller';

import {
  GymService,
  GymFollowerService,
  GymManagerService,
  GymManagerOverviewService,
  GymManagerQualificationService,
  GymManagerSpecializedInWorkoutService,
  GymMembershipPlanService,
  GymManagerFollowerService,
  GymManagerRequestService,
  GymMembershipService,
  GymSpecializedInWorkoutService,
  GymSpecializedInNutritionService,
  GymManagerSpecializedInNutritionService,
  GymOpenDayService,
} from './service';

import {
  GymEntity,
  GymFollowerEntity,
  GymManagerEntity,
  GymOpenDayEntity,
  GymManagerOverviewEntity,
  GymManagerQualificationEntity,
  GymManagerSpecializedInWorkoutEntity,
  GymMembershipPlanEntity,
  GymManagerFollowerEntity,
  GymManagerRequestEntity,
  GymMembershipEntity,
  GymSpecializedInWorkoutEntity,
  GymSpecializedInNutritionEntity,
      GymManagerSpecializedInNutritionEntity,
} from './entity';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      GymEntity,
      GymFollowerEntity,
      GymManagerEntity,
      GymOpenDayEntity,
      GymManagerOverviewEntity,
      GymManagerQualificationEntity,
      GymManagerSpecializedInWorkoutEntity,
      GymMembershipPlanEntity,
      GymManagerFollowerEntity,
      GymManagerRequestEntity,
      GymMembershipEntity,
      GymSpecializedInWorkoutEntity,
      GymSpecializedInNutritionEntity,
      GymManagerSpecializedInNutritionEntity,
    ]),
  ],
  controllers: [
    GymController,
    GymFollowerController,
    GymManagerController,
    GymManagerOverviewController,
    GymManagerQualificationController,
    GymManagerSpecializedInWorkoutController,
    GymMembershipPlanController,
    GymManagerFollowerController,
    GymManagerRequestController,
    GymMembershipController,
    GymSpecializedInWorkoutController,
    GymSpecializedInNutritionController,
    GymManagerSpecializedInNutritionController,
    GymOpenDayController,
  ],
  providers: [
    GymService,
    GymFollowerService,
    GymManagerService,
    GymManagerOverviewService,
    GymManagerQualificationService,
    GymManagerSpecializedInWorkoutService,
    GymMembershipPlanService,
    GymManagerFollowerService,
    GymManagerRequestService,
    GymMembershipService,
    GymSpecializedInWorkoutService,
    GymSpecializedInNutritionService,
    GymManagerSpecializedInNutritionService,
    GymOpenDayService,
  ],
  exports: [
    GymService,
    GymFollowerService,
    GymManagerService,
    GymManagerOverviewService,
    GymManagerQualificationService,
    GymManagerSpecializedInWorkoutService,
    GymMembershipPlanService,
    GymManagerFollowerService,
    GymManagerRequestService,
    GymMembershipService,
    GymSpecializedInWorkoutService,
    GymSpecializedInNutritionService,
    GymManagerSpecializedInNutritionService,
    GymOpenDayService,
  ],
})
export class GymModule {}
