import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  ContentEntity,
  ContentTextEntity,
  ContentTextareaEntity,
  ContentAccordionEntity,
  ContentCarouselEntity,
  ContentCommitmentEntity,
  ContentConsumptionEntity,
  ContentChatWithCoachEntity,
  ContentSusbcriptionPlanEntity,
  ContentRecipeEntity,
  ContentChallengesEntity,
  ContentFaqItemEntity,
  ContentAccordionItemEntity,
  ContentCarouselItemEntity,
  ContentChallengesItemEntity,
  ContentCommitmentItemEntity,
  ContentConsumptionItemEntity,
  ContentSusbcriptionPlanItemEntity,
  ContentGoalsItemEntity,
  ContentGoalsEntity,
  ContentImageEntity,
} from './entity';

import {
  ContentAccordionItemService,
  ContentAccordionService,
  ContentCarouselItemService,
  ContentCarouselService,
  ContentChallengesItemService,
  ContentChallengesService,
  ContentChatWithCoachService,
  ContentCommitmentItemService,
  ContentCommitmentService,
  ContentConsumptionItemService,
  ContentConsumptionService,
  ContentFaqItemService,
  ContentGoalsItemService,
  ContentGoalsService,
  ContentImageService,
  ContentService,
  ContentSusbcriptionPlanItemService,
  ContentSusbcriptionPlanService,
  ContentTextareaService,
  ContentTextService,
} from './service';

import {
  ContentAccordionController,
  ContentAccordionItemController,
  ContentCarouselController,
  ContentCarouselItemController,
  ContentChallengesController,
  ContentChallengesItemController,
  ContentChatWithCoachController,
  ContentCommitmentController,
  ContentCommitmentItemController,
  ContentConsumptionController,
  ContentConsumptionItemController,
  ContentController,
  ContentFaqItemController,
  ContentGoalsController,
  ContentGoalsItemController,
  ContentSusbcriptionPlanController,
  ContentSusbcriptionPlanItemController,
  ContentTextareaController,
  ContentTextController,
} from './controller';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      // Core entities
      ContentEntity,
      ContentTextEntity,
      ContentTextareaEntity,
      ContentAccordionEntity,
      ContentCarouselEntity,
      ContentRecipeEntity,
      ContentChallengesEntity,
      ContentCommitmentEntity,
      ContentConsumptionEntity,
      ContentChatWithCoachEntity,
      ContentSusbcriptionPlanEntity,
      ContentGoalsEntity,
      ContentImageEntity,
      // Item entities
      ContentAccordionItemEntity,
      ContentCarouselItemEntity,
      ContentChallengesItemEntity,
      ContentCommitmentItemEntity,
      ContentConsumptionItemEntity,
      ContentSusbcriptionPlanItemEntity,
      ContentFaqItemEntity,
      ContentGoalsItemEntity,
    ]),
  ],
  controllers: [
    // Core controllers
    ContentController,
    ContentTextController,
    ContentTextareaController,
    ContentAccordionController,
    ContentCarouselController,
    ContentChallengesController,
    ContentCommitmentController,
    ContentConsumptionController,
    ContentChatWithCoachController,
    ContentSusbcriptionPlanController,
    ContentGoalsController,
    // Item controllers
    ContentAccordionItemController,
    ContentCarouselItemController,
    ContentChallengesItemController,
    ContentCommitmentItemController,
    ContentConsumptionItemController,
    ContentSusbcriptionPlanItemController,
    ContentFaqItemController,
    ContentGoalsItemController,
  ],
  providers: [
    // Core services
    ContentService,
    ContentTextService,
    ContentTextareaService,
    ContentAccordionService,
    ContentCarouselService,
    ContentChallengesService,
    ContentCommitmentService,
    ContentConsumptionService,
    ContentChatWithCoachService,
    ContentSusbcriptionPlanService,
    ContentGoalsService,
    ContentImageService,
    // Item services
    ContentAccordionItemService,
    ContentCarouselItemService,
    ContentChallengesItemService,
    ContentCommitmentItemService,
    ContentConsumptionItemService,
    ContentSusbcriptionPlanItemService,
    ContentFaqItemService,
    ContentGoalsItemService,
  ],
  exports: [
    // Core services
    ContentService,
    ContentTextService,
    ContentTextareaService,
    ContentAccordionService,
    ContentCarouselService,
    ContentChallengesService,
    ContentCommitmentService,
    ContentConsumptionService,
    ContentChatWithCoachService,
    ContentSusbcriptionPlanService,
    ContentGoalsService,
    ContentImageService,
    // Item services
    ContentAccordionItemService,
    ContentCarouselItemService,
    ContentChallengesItemService,
    ContentCommitmentItemService,
    ContentConsumptionItemService,
    ContentSusbcriptionPlanItemService,
    ContentFaqItemService,
    ContentGoalsItemService,
  ],
})
export class ContentModule {}
