import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  // Core Entities
  ContentAccordionEntity,
  ContentCarouselEntity,
  ContentChallengesEntity,
  ContentChatWithCoachEntity,
  ContentCommitmentEntity,
  ContentConsumptionEntity,
  ContentEntity,
  ContentEquipmentEntity,
  ContentFaqEntity,
  ContentGoalsEntity,
  ContentImageEntity,
  ContentInformationEntity,
  ContentInstructionsEntity,
  ContentOrderedlistEntity,
  ContentPrerequisitesEntity,
  ContentRecipeEntity,
  ContentSusbcriptionPlanEntity,
  ContentTextEntity,
  ContentTextareaEntity,
  ContentTipsEntity,
  ContentUnorderedlistEntity,
  ContentUsersupportEntity,
  ContentVideoEntity,
  ContentWarningEntity,
  ContentWorkoutEntity,
  // Item Entities
  ContentAccordionItemEntity,
  ContentCarouselItemEntity,
  ContentChallengesItemEntity,
  ContentCommitmentItemEntity,
  ContentConsumptionItemEntity,
  ContentEquipmentItemEntity,
  ContentFaqItemEntity,
  ContentGoalsItemEntity,
  ContentOrderedlistItemEntity,
  ContentPrerequisitesItemEntity,
  ContentSusbcriptionPlanItemEntity,
  ContentTipsItemEntity,
  ContentUnorderedlistItemEntity,
  ContentGalleryEntity,
} from './entity';

import {
  // Core Services
  ContentAccordionService,
  ContentCarouselService,
  ContentChallengesService,
  ContentChatWithCoachService,
  ContentCommitmentService,
  ContentConsumptionService,
  ContentService,
  ContentEquipmentService,
  ContentFaqService,
  ContentGoalsService,
  ContentImageService,
  ContentInformationService,
  ContentInstructionsService,
  ContentOrderedlistService,
  ContentPrerequisitesService,
  ContentRecipeService,
  ContentSusbcriptionPlanService,
  ContentTextService,
  ContentTextareaService,
  ContentTipsService,
  ContentUnorderedlistService,
  ContentUsersupportService,
  ContentVideoService,
  ContentWarningService,
  ContentWorkoutService,
  ContentGalleryService,

  // Item Services
  ContentAccordionItemService,
  ContentCarouselItemService,
  ContentChallengesItemService,
  ContentCommitmentItemService,
  ContentConsumptionItemService,
  ContentEquipmentItemService,
  ContentFaqItemService,
  ContentGoalsItemService,
  ContentOrderedlistItemService,
  ContentPrerequisitesItemService,
  ContentSusbcriptionPlanItemService,
  ContentTipsItemService,
  ContentUnorderedlistItemService,
} from './service';

import {
  ContentAccordionController,
  ContentCarouselController,
  ContentChallengesController,
  ContentChatWithCoachController,
  ContentCommitmentController,
  ContentConsumptionController,
  ContentController,
  ContentEquipmentController,
  ContentFaqController,
  ContentGoalsController,
  ContentImageController,
  ContentInformationController,
  ContentInstructionsController,
  ContentOrderedlistController,
  ContentPrerequisitesController,
  ContentRecipeController,
  ContentSusbcriptionPlanController,
  ContentTextController,
  ContentTextareaController,
  ContentTipsController,
  ContentUnorderedlistController,
  ContentUsersupportController,
  ContentVideoController,
  ContentWarningController,
  ContentWorkoutController,
  ContentGalleryController,

  ContentAccordionItemController,
  ContentCarouselItemController,
  ContentChallengesItemController,
  ContentCommitmentItemController,
  ContentConsumptionItemController,
  ContentEquipmentItemController,
  ContentFaqItemController,
  ContentGoalsItemController,
  ContentOrderedlistItemController,
  ContentPrerequisitesItemController,
  ContentSusbcriptionPlanItemController,
  ContentTipsItemController,
  ContentUnorderedlistItemController,
} from './controller';

@Module({
  imports: [
    TypeOrmModule.forFeature([
    // Core Entities
    ContentAccordionEntity,
    ContentCarouselEntity,
    ContentChallengesEntity,
    ContentChatWithCoachEntity,
    ContentCommitmentEntity,
    ContentConsumptionEntity,
    ContentEntity,
    ContentEquipmentEntity,
    ContentFaqEntity,
    ContentGoalsEntity,
    ContentImageEntity,
    ContentInformationEntity,
    ContentInstructionsEntity,
    ContentOrderedlistEntity,
    ContentPrerequisitesEntity,
    ContentRecipeEntity,
    ContentSusbcriptionPlanEntity,
    ContentTextEntity,
    ContentTextareaEntity,
    ContentTipsEntity,
    ContentUnorderedlistEntity,
    ContentUsersupportEntity,
    ContentVideoEntity,
    ContentWarningEntity,
    ContentWorkoutEntity,
    ContentGalleryEntity,

    // Item Entities
    ContentAccordionItemEntity,
    ContentCarouselItemEntity,
    ContentChallengesItemEntity,
    ContentCommitmentItemEntity,
    ContentConsumptionItemEntity,
    ContentEquipmentItemEntity,
    ContentFaqItemEntity,
    ContentGoalsItemEntity,
    ContentOrderedlistItemEntity,
    ContentPrerequisitesItemEntity,
    ContentSusbcriptionPlanItemEntity,
    ContentTipsItemEntity,
    ContentUnorderedlistItemEntity,
    ]),
  ],
  controllers: [
    // Core controllers
    ContentAccordionController,
    ContentCarouselController,
    ContentChallengesController,
    ContentChatWithCoachController,
    ContentCommitmentController,
    ContentConsumptionController,
    ContentController,
    ContentEquipmentController,
    ContentFaqController,
    ContentGoalsController,
    ContentImageController,
    ContentInformationController,
    ContentInstructionsController,
    ContentOrderedlistController,
    ContentPrerequisitesController,
    ContentRecipeController,
    ContentSusbcriptionPlanController,
    ContentTextController,
    ContentTextareaController,
    ContentTipsController,
    ContentUnorderedlistController,
    ContentUsersupportController,
    ContentVideoController,
    ContentWarningController,
    ContentWorkoutController,
    ContentGalleryController,

    // Item controllers
    ContentAccordionItemController,
    ContentCarouselItemController,
    ContentChallengesItemController,
    ContentCommitmentItemController,
    ContentConsumptionItemController,
    ContentEquipmentItemController,
    ContentFaqItemController,
    ContentGoalsItemController,
    ContentOrderedlistItemController,
    ContentPrerequisitesItemController,
    ContentSusbcriptionPlanItemController,
    ContentTipsItemController,
    ContentUnorderedlistItemController,
  ],
  providers: [
    // Core Services
    ContentAccordionService,
    ContentCarouselService,
    ContentChallengesService,
    ContentChatWithCoachService,
    ContentCommitmentService,
    ContentConsumptionService,
    ContentService,
    ContentEquipmentService,
    ContentFaqService,
    ContentGoalsService,
    ContentImageService,
    ContentInformationService,
    ContentInstructionsService,
    ContentOrderedlistService,
    ContentPrerequisitesService,
    ContentRecipeService,
    ContentSusbcriptionPlanService,
    ContentTextService,
    ContentTextareaService,
    ContentTipsService,
    ContentUnorderedlistService,
    ContentUsersupportService,
    ContentVideoService,
    ContentWarningService,
    ContentWorkoutService,
    ContentGalleryService,

    // Item Services
    ContentAccordionItemService,
    ContentCarouselItemService,
    ContentChallengesItemService,
    ContentCommitmentItemService,
    ContentConsumptionItemService,
    ContentEquipmentItemService,
    ContentFaqItemService,
    ContentGoalsItemService,
    ContentOrderedlistItemService,
    ContentPrerequisitesItemService,
    ContentSusbcriptionPlanItemService,
    ContentTipsItemService,
    ContentUnorderedlistItemService,
  ],
  exports: [
    // Core Services
    ContentAccordionService,
    ContentCarouselService,
    ContentChallengesService,
    ContentChatWithCoachService,
    ContentCommitmentService,
    ContentConsumptionService,
    ContentService,
    ContentEquipmentService,
    ContentFaqService,
    ContentGoalsService,
    ContentImageService,
    ContentInformationService,
    ContentInstructionsService,
    ContentOrderedlistService,
    ContentPrerequisitesService,
    ContentRecipeService,
    ContentSusbcriptionPlanService,
    ContentTextService,
    ContentTextareaService,
    ContentTipsService,
    ContentUnorderedlistService,
    ContentUsersupportService,
    ContentVideoService,
    ContentWarningService,
    ContentWorkoutService,
    ContentGalleryService,

    // Item Services
    ContentAccordionItemService,
    ContentCarouselItemService,
    ContentChallengesItemService,
    ContentCommitmentItemService,
    ContentConsumptionItemService,
    ContentEquipmentItemService,
    ContentFaqItemService,
    ContentGoalsItemService,
    ContentOrderedlistItemService,
    ContentPrerequisitesItemService,
    ContentSusbcriptionPlanItemService,
    ContentTipsItemService,
    ContentUnorderedlistItemService,
  ],
})
export class ContentModule {}
